// Collection of 10 books
const booksData = [
    {
      "title": "The Great Gatsby",
      "author": "F. Scott Fitzgerald",
      "genre": "Classic",
      "price": 15,
      "rating": 5,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780743273565",
    },
    {
      "title": "To Kill a Mockingbird",
      "author": "Harper Lee",
      "genre": "Fiction",
      "price": 18,
      "rating": 4,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780061120084",
    },
    {
      "title": "1984",
      "author": "George Orwell",
      "genre": "Dystopian",
      "price": 22,
      "rating": 2,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780451524935",
    },
    {
      "title": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "genre": "Fantasy",
      "price": 25,
      "rating": 3,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780345339683",
    },
    {
      "title": "Harry Potter",
      "author": "J.K. Rowling",
      "genre": "Fantasy",
      "price": 30,
      "rating": 5,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780590353427",
    },
    {
      "title": "The Catcher in the Rye",
      "author": "J.D. Salinger",
      "genre": "Coming-of-Age",
      "price": 20,
      "rating": 3,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780241950425",
    },
    {
      "title": "Pride and Prejudice",
      "author": "Jane Austen",
      "genre": "Romance",
      "price": 16,
      "rating": 2,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780679783268",
    },
    {
      "title": "The Lord of the Rings",
      "author": "J.R.R. Tolkien",
      "genre": "Fantasy",
      "price": 35,
      "rating": 4,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780345339706",
    },
    {
      "title": "Brave New World",
      "author": "Aldous Huxley",
      "genre": "Dystopian",
      "price": 28,
      "rating": 3,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780060850524",
    },
    {
      "title": "The Hunger Games",
      "author": "Suzanne Collins",
      "genre": "Dystopian",
      "price": 26,
      "rating": 4,
      "imageUrl": "https://images.penguinrandomhouse.com/cover/9780439023481",
    },
  ];
  
module.exports = booksData;
